{% set version = "2.0.0" %}

package:
  name: tablib
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/tablib/tablib-{{ version }}.tar.gz
  sha256: 8cc2fa10bc37219ac5e76850eb7fbd50de313c7a1a7895c44af2a8dd206b7be7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
    - setuptools_scm
  run:
    - python >=3.5
    - setuptools
    - markuppy
    - odfpy
    - openpyxl >=2.4.0
    - pandas
    - pyyaml
    - tabulate
    - xlrd
    - xlwt

test:
  requires:
    - pip
    - pandas
  imports:
    - tablib
    - tablib.formats
    - tablib.packages
  source_files:
    - tests/test_tablib.py
  commands:
    - python tests/test_tablib.py
    - pip check

about:
  home: https://pypi.org/project/tablib/
  summary: Format agnostic tabular data library (XLS, JSON, YAML, CSV)
  dev_url: https://github.com/jazzband/tablib
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
