{% set version = "0.13.0" %}

package:
  name: tablib
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/tablib/tablib-{{ version }}.tar.gz
  sha256: 5f33c079b07eb10cf9c4b4696add2ecf32c89db7729240546ecdcd5c92f67e13

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - odfpy
    - openpyxl
    - pandas
    - pyyaml
    - unicodecsv
    - xlrd
    - xlrd
    - xlwt

test:
  imports:
    - tablib
    - tablib.formats
    - tablib.packages
  source_files:
    - test_tablib.py
  commands:
    - python test_tablib.py  # [not win]

about:
  home: http://python-tablib.org
  license: MIT
  license_file: LICENSE
  summary: 'Format agnostic tabular data library (XLS, JSON, YAML, CSV)'

extra:
  recipe-maintainers:
    - ocefpaf
