{% set version = "0.11.5" %}

package:
  name: tablib
  version: {{ version }}

source:
  fn: tablib-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/t/tablib/tablib-{{ version }}.tar.gz
  sha256: 27aafe2bf6573472f4ab330b2e46e9ebf01942a204bfaee784191848411afe05

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - xlrd
    - odfpy
    - openpyxl
    - unicodecsv
    - xlrd
    - xlwt
    - pyyaml

test:
  imports:
    - tablib
    - tablib.formats
    - tablib.packages
  source_files:
    - test_tablib.py
  commands:
    - python test_tablib.py  # [not win]

about:
  home: http://python-tablib.org
  license: MIT
  license_file: LICENSE
  summary: 'Format agnostic tabular data library (XLS, JSON, YAML, CSV)'

extra:
  recipe-maintainers:
    - ocefpaf
