{% set version = "1.0.0" %}

package:
  name: tablib
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/tablib/tablib-{{ version }}.tar.gz
  sha256: ff3172802e8dd7fb795867942f5238f6c90e2d4e90ad6233c1a796cdfc63bb35

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.5
    - pip
    - setuptools_scm
  run:
    - python >=3.5
    - setuptools
    - markuppy
    - odfpy
    - openpyxl >=2.4.0
    - pandas
    - pyyaml
    - tabulate
    - xlrd
    - xlwt

test:
  requires:
    - pandas
  imports:
    - tablib
    - tablib.formats
    - tablib.packages
  source_files:
    - tests/test_tablib.py
  commands:
    - python tests/test_tablib.py

about:
  home: http://python-tablib.org
  license: MIT
  license_file: LICENSE
  summary: 'Format agnostic tabular data library (XLS, JSON, YAML, CSV)'

extra:
  recipe-maintainers:
    - ocefpaf
