{% set version = "0.14.0" %}

package:
  name: tablib
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/tablib/tablib-{{ version }}.tar.gz
  sha256: 6336e7aa3f0e5894b47270a3dc639cc2e78eb823c7ccb8c4512fb408cdc18d08

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
    - setuptools_scm
  run:
    - python
    - setuptools
    - odfpy
    - openpyxl >=2.4.0
    - backports.csv
    - markuppy
    - xlrd
    - xlwt
    - pyyaml

test:
  requires:
    - pandas
  imports:
    - tablib
    - tablib.formats
    - tablib.packages
  source_files:
    - tests/test_tablib.py
  commands:
    - python tests/test_tablib.py

about:
  home: http://python-tablib.org
  license: MIT
  license_file: LICENSE
  summary: 'Format agnostic tabular data library (XLS, JSON, YAML, CSV)'

extra:
  recipe-maintainers:
    - ocefpaf
