{% set version = "3.3.0" %}

package:
  name: tablib
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/tablib/tablib-{{ version }}.tar.gz
  sha256: 11e02a6f81d256e0666877d8397972d10302307a54c04fd7157e92faf740cb10

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools_scm
  run:
    - python >=3.7
    - setuptools
    - markuppy
    - odfpy
    - openpyxl >=2.4.0
    - pandas
    - pyyaml
    - tabulate
    - xlrd
    - xlwt

test:
  requires:
    - pip
    - pandas
  imports:
    - tablib
    - tablib.formats
    - tablib.packages
  source_files:
    - tests/test_tablib.py
  commands:
    - python tests/test_tablib.py
    - pip check

about:
  home: https://pypi.org/project/tablib/
  summary: Format agnostic tabular data library (XLS, JSON, YAML, CSV)
  dev_url: https://github.com/jazzband/tablib
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
