travis:
  secure:
    BINSTAR_TOKEN: SdlC0qGhdbNMdt9Oqg288cpgiLjTfuG9wCNmb1LyEy3bts8D+drq+ny4wFE/KpNGmJwdTmxcRDuTwIwPA6nek3x4Mqxp7knuYz/3uaVl01K7VHRZHC3IyrOPUi7irh6IlrA6BKaYRB11kEzMpTuWibFcENnN+rTRlC6Rbn+N7Mu8xaU6gZcHIMdZEm91PEB3msq7hwqAr6ol6arCdx+V4AszQan3qMVLlRseLFO2W5X3YSA2QeZQE67078+r1IIWkbHOXOCqB/uK+Q0QdrHPoAqgeKONCoAM7OVJNsk0EF7l79+hLF7q3va0lOKpb0/ZKtrvIK6mgOkNH8/I/7Fvj6u99VLc8uw4he4PdkcRbMqSDPJOLcAhhQEpeNw7kqmCPFv0ReFoSJbMRMKy5C83AxeLw1v4lbqLNL52DXUm0XueNxvbeDo03Zgkt44u0fm5pctOGQ2vIuh/agZLHFrLTIzHWsVc/lMgC/pPhKEIWRGo6/Xmp5vXrODnxIwxymM9OBu3Pk68CvA38r8aDuBygzGhGkC1L09X5o48M2MXf1TdiTfu3wIBhs1buJhz+URCkFBvZ/QbOC8NhONjhIYnHOoBJ1BcTluE0OgDP64ehBZvliOA5VrFuVQgQDv8xLiHZHbZ3CTHwuBIqSkpblhvLRiKyuBPFEJMIP8VUanW/9s=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
