travis:
  secure:
    BINSTAR_TOKEN: NShJqMV5263I9UP+NC49J0uf0i7tHhq70hJTiPl/0Yb4FpMigKLBVXQotEvjorFypA2zKXWGLXo+yGsJuwlCRlZ416FPNFZRwNUwuXiK6vRK62H2mEst5e5v6KMoWXyPeFXl3mFwl7LEtwOS5Gr9ZZiLtVsrHC3sDywREzyVOPEJrO6rLWD6jI7Ane6M2kQ9Y1aApXGCdDpY4B9/4G0BwlTBWymugSb9ATCXwDqDrvYkv1FzC2wjVyyEK4u4+zS4e+pct4/vLjA+KNlaulHhKEAFTOxWyzlC2bzqyZAo/nuV5DJK4vGaj6dnrt9+Tg7wFHTpkfC7zGr3hyOJDnVKIDKxEc60HGlA1qPsgOyfKb6zH0WWIXRHmrm23dps5ekaUkSFmmeOp3JpGiEiIuDg83lkOqkpbbBQe2rvSoaNuU/IiCVwr5sMt6GNeQ0z/YhkHP1UBX//kHpkqb+uMnucKfS46STwcC/MXEyzgqhvC474vdn76a6Kox8RXgB7Mr6VdZ3mJho9q3Vtyfop1uk6fshwgv+z2aEtnHlqrOkVkxSbEuFZL5HIUr4LWssmqIQdSiET+pMcrJwD20UvQBZDukrObquwrkzy9BDeRIOoAhufX+eQo3YRVqVmD+Aam7xQQvdy3nXQ8MCuD3ZCpEb90fwIC+ros2wIjJafVB6N3JM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
