travis:
  secure:
    BINSTAR_TOKEN: cAfGXAczcNMG8MUJ3AvJhcSTUEWI05mEH/zFRxjZI8YW0lJcxuWRLpKO2z4wKu/zCVbYtIkrntaks/WTYjD1X3VH1Q2q/wV7o3j5W2urSQ8MN03f679cHnMYJLuGpU6kTnAF+LSwFT8XYmy9Rg0YoKv5Blkx54VrrERfegCYfbWrIWmqRkmJzeuR9X3I+PdbCr6nRfcADON0DANxQBCGYxl9CmQjIzb/N+/feTgy3iVq/UHrhGJIO+V3hoLmbrxy+3NfKeROyqgr971RUnh3lPCAMOPrtZsm+bA1lrxVfaw5aAFW0eUCQoZSAMjOyuOGoby7Ph9u/wkMwp+dAzXdpHp/RjRkWtmTvNYJc77iAgea2zu7Y4EFUS/3ZKvZRsnQ6Ber2KrHXqy8irqVe/jPdiSHZ13KcBWkWM5wsFh/jX0iRgFWnrY4wzEc5RwbYFWkag3/nb5ZUk1nC2XfA7f25vt9CJJ922U+q8uanew9CCyJ0Cxl0RGt6yHAbc++/7pSgDHhIGYIfLbOfDOOqBgMSWBu9idEOBfLjmMJVmFSmJASRnLqTxvLvMQHhYmGxcVbA6uBxgBp/nMA3bE8OIqJR9hzlDr+TZuOTvWdHVAyYgkTQx0W7rzziP/MWDO3JyIASqGzG31AQQiNIwh0b8mkrctxSDpefL/Brc3x3XnZdD4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
